services:
  mongodb:
    image: mongo:7.0
    container_name: meta-vis-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: meta-vis-dev

volumes:
  mongodb_data: