services:
  mongodb:
    image: mongo:7.0
    container_name: meta-vis-mongodb
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_DB_NAME: ${MONGODB_DB_NAME}
    env_file:
      - .env

  minio:
    image: minio/minio
    container_name: meta-vis-minio
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpassword
    command: server /data --console-address ":9001"

volumes:
  mongodb_data:
  minio_data: